print("err to deal with")
error("some mistake",1)
print("continue to process")